apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-grafana-alerts
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    grafana_alert: "1"
data:
  alerts.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: devops-alerts
          folder: devops
          interval: 1m
          rules:
            - uid: 1234-devops
              title: pod-restarts-devops
              condition: C
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    disableTextWrap: false
                    editorMode: code
                    expr: group by (namespace, pod) (increase(kube_pod_container_status_restarts_total{namespace="monitoring"}[1m]) > 1)
                    fullMetaSearch: false
                    includeNullMetadata: true
                    instant: false
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: true
                    refId: A
                    useBackend: false
                - refId: reducer
                  queryType: expression
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                    datasource:
                        name: Expression
                        type: __expr__
                        uid: __expr__
                    expression: A
                    intervalMs: 1000
                    maxDataPoints: 43200
                    reducer: last
                    refId: reducer
                    type: reduce
                - refId: C
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: reducer
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: C
                    type: threshold
              noDataState: OK
              execErrState: Error
              for: 1m
              annotations: {}
              labels: {}
              isPaused: false
