apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-grafana-alerts
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    grafana_alert: "1"
data:
  alerts.yaml: |
    apiVersion: 1
    groups:
        - orgId: 1
          name: devops-alerts
          folder: devops
          interval: 1m
          rules:
            - uid: 1234-devops
              title: pod-restarts-devops
              condition: A
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: prometheus
                  model:
                    disableTextWrap: false
                    editorMode: code
                    expr: group by (namespace, pod) (increase(kube_pod_container_status_restarts_total{namespace="monitoring"}[1m]) > 1)
                    fullMetaSearch: false
                    includeNullMetadata: true
                    instant: false
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: true
                    refId: A
                    useBackend: false
              noDataState: OK
              execErrState: Error
              for: 1m
              annotations: {}
              labels:
                team: devops
              isPaused: false
